cotxes/urls.py
# -*- coding: utf8 -*-
from django.conf.urls import patterns, url
from cotxes import views
#Fitxer URLS de l'aplicació cotxes
urlpatterns = patterns('',
    url(r'^llistatReparacions/$', views.llistatReparacions, name='llistatReparacions'),
    url(r'^novaReparacio/$', views.vw_reparacio, name='novaReparacio'),
    url(r'^editar_reparacio/(?P<id_reparacio>\d+)$', views.vw_reparacio, name='edita_reparacio'),
)

tallerjf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'cotxes.views.home', name='home'),
    url(r'^cotxes/', include('cotxes.urls', namespace="cotxesns")),
    url(r'^admin/', include(admin.site.urls)),
)

cotxes/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from personal.models import Tecnic
# Create your models here.

COLORS_COTXE = (
                ('blanc', 'blanc'),
                ('groc', 'groc'),
                ('negre', 'negre'),
                ('vermell','vermell'),
                )
#Model d'un cotxe
class Cotxe(models.Model):
    matricula = models.CharField(max_length=8, unique=True)
    nomPropietari = models.CharField(max_length=100)
    nomMarca = models.CharField(max_length=100)
    nomModel = models.CharField(max_length=100)
    color = models.CharField(max_length=7, choices=COLORS_COTXE)
    dataMatriculacio = models.DateField()
    esImportat = models.BooleanField()
    
    
    def __unicode__(self):
        return self.matricula

#Model de reparacio
class Reparacio(models.Model):
    cotxe = models.ForeignKey(Cotxe)
    diaEntradaTaller = models.DateField()
    kilometres = models.CharField(max_length=15)
    descripcioAvaria = models.CharField(max_length=100)
    tecnicRepara = models.ForeignKey(Tecnic)
    diaSortidaTaller = models.DateField(blank = True, null = True)
    
    def __unicode__(self):
        return self.descripcioAvaria

personal/models.py
from django.db import models

# Create your models here.
#Model de Tecnic
class Tecnic(models.Model):
    numSegSocial = models.CharField(max_length=15)
    nom = models.CharField(max_length=100)
    esBaixa = models.BooleanField()
    
    def __unicode__(self):
        return self.nom

cotxes/forms.py
from django.forms import ModelForm
from cotxes.models import Reparacio

#Formulari de model per entrar o editar reparacions

class ReparacioForm(ModelForm):
    class Meta:
        model = Reparacio
        fields = ['cotxe', 'diaEntradaTaller', 'kilometres', 'descripcioAvaria', 'tecnicRepara', 'diaSortidaTaller']

cotxes/views.py
# -*- encoding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from cotxes.models import Cotxe, Reparacio
from cotxes.forms import ReparacioForm
from django.contrib import messages
from django.http.response import HttpResponseRedirect
# Create your views here.
#Vista home es carrega al entrar a l'arrel
def home(request):
    tots_cotxes = Cotxe.objects.filter(reparacio__diaSortidaTaller__isnull= True)
    context = {'cotxes':tots_cotxes}
    return render(request, 'cotxes/home.html', context)
#Vista per entrar o editar una reparació
def vw_reparacio(request, id_reparacio = None):
    if id_reparacio is not None:
        reparacio = get_object_or_404(Reparacio, pk=id_reparacio)
    else:
        reparacio = Reparacio()    
    if request.method == 'POST':
        
        form = ReparacioForm(request.POST, instance = reparacio)
        if form.is_valid():
            form.save()
            messages.success(request, 'Reparació introduida correctament')
            return HttpResponseRedirect('/')
        else:
            messages.error(request, 'Ep! Hi ha hagut un error!')
    else:
        form = ReparacioForm(instance=reparacio) 
        
    return render(request, 'cotxes/form.html', {
        'form': form,
    })
#Vista per llistat les reparacions
def llistatReparacions(request):
    reparacions = Reparacio.objects.all()
    context = {'reparacions': reparacions}
    return render(request, 'cotxes/llistat_reparacions.html', context)

personal/views.py
from django.shortcuts import render

# Create your views here.

cotxes/templates/cotxes/form.html
{% extends "base.html" %}
{% block title %}
Afegir dades
{% endblock %}

{% block content %}
<h1>Afegir noves dades</h1>
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>
{% endblock %}

cotxes/templates/cotxes/home.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}
<h1>Benvinguts a la web de tallerjf </h1>
<b>Llistat de les matricules dels cotxes que hi ha al taller</b>


{% if cotxes %}
<ul>
	{% for cotxe in cotxes %}
	<li>
		{{ cotxe.matricula }}

	</li>
	{% endfor %}
</ul>
{% else %}
<h2>No hi ha cotxes al taller</h2>
{% endif %}
<a href="{% url 'cotxesns:novaReparacio' %}">Afegir una nova reparació</a>
<a href="{% url 'cotxesns:llistatReparacions' %}">Llistat de les reparacions realitzades</a>
{% endblock %}

cotxes/templates/cotxes/llistat_reparacions.html
{% extends "base.html" %}
{% block title %}Llistat reparacions{% endblock %}

{% block content %}
<h1>Llistat de reparacions</h1>

<ul>
	{% for r in reparacions %}
	<li>
		<a href="{% url 'cotxesns:edita_reparacio' r.id %}">{{ r.descripcioAvaria }}</a>
		
	</li>
	{% endfor %}
</ul>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ca">
	<head>
		<meta charset="utf-8">

		<title>{% block title %} base {% endblock %}</title>
		{% block estil %}
		<style>
			body {
				background-color: #CCCCCC;
			}
		</style> {% endblock %}

	</head>

	<body>
		{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li
			{% if message.tags %} class="{{message.tags}}"{% endif %}>
				{{ message }}
			</li>
			{% endfor %}
		</ul>
		{% endif %}

		{% block content %}
		patata
		{% endblock %}
	</body>
</html>